# Generated by Django 2.2.3 on 2019-08-30 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_auto_20190806_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('get_code_type', models.CharField(choices=[('git', 'Git'), ('wget', 'Wget')], default='git', max_length=10, verbose_name='获取代码方式')),
                ('web_root', models.CharField(max_length=100, verbose_name='WebRoot')),
                ('exclude_file', models.TextField(blank=True, verbose_name='排除文件')),
                ('pre_script', models.FilePathField(match='\\.py$|\\.rb$|\\.sh$|\\.php$|\\.java$|\\.pl$|\\.go$', path='/data/.virtualenvs/small_platform/project_scripts', recursive=True, verbose_name='前执行脚本')),
                ('post_script', models.FilePathField(match='\\.py$|\\.rb$|\\.sh$|\\.php$|\\.java$|\\.pl$|\\.go$', path='/data/.virtualenvs/small_platform/project_scripts', recursive=True, verbose_name='后执行脚本')),
                ('version_count', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49)], default=20, verbose_name='保留版本数量')),
                ('developer', models.ManyToManyField(blank=True, related_name='users_developers', to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_hosts', to='assets.Service')),
                ('operator', models.ManyToManyField(blank=True, related_name='users_operators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '业务/项目',
                'verbose_name_plural': '业务/项目',
            },
        ),
        migrations.CreateModel(
            name='Wget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='下载地址')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_wget', to='release.Project', verbose_name='所属业务')),
            ],
            options={
                'verbose_name': 'Wget获取',
                'verbose_name_plural': 'Wget获取',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64, verbose_name='发布版本')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='发布功能')),
                ('if_test', models.BooleanField(default=False, verbose_name='是否测试')),
                ('released_hosts', models.TextField(blank=True, null=True, verbose_name='已发布的机器')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('record_time', models.DateTimeField(auto_now=True, verbose_name='事件时间')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_record', to='release.Project', verbose_name='所属业务')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_publisher', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_submitter', to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
            ],
            options={
                'verbose_name': '发布记录',
                'verbose_name_plural': '发布记录',
            },
        ),
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=100, verbose_name='仓库代码地址')),
                ('branch', models.CharField(default='master', max_length=32, verbose_name='分支名称')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_git', to='release.Project', verbose_name='所属业务')),
            ],
            options={
                'verbose_name': 'Git获取',
                'verbose_name_plural': 'Git获取',
            },
        ),
    ]
