# Generated by Django 2.2.3 on 2019-09-01 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_project_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='users_developers', to=settings.AUTH_USER_MODEL, verbose_name='开发'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_hosts', to='assets.Service', verbose_name='服务组'),
        ),
        migrations.AlterField(
            model_name='project',
            name='operator',
            field=models.ManyToManyField(blank=True, related_name='users_operators', to=settings.AUTH_USER_MODEL, verbose_name='运维'),
        ),
    ]
