# Generated by Django 2.2.3 on 2019-09-01 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0003_auto_20190901_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='if_test',
        ),
        migrations.AddField(
            model_name='record',
            name='if_approve',
            field=models.BooleanField(default=False, verbose_name='是否审批'),
        ),
        migrations.CreateModel(
            name='ApproveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='审批详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_approve', to=settings.AUTH_USER_MODEL, verbose_name='审批人员')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_approve', to='release.Record', verbose_name='审批记录')),
            ],
            options={
                'verbose_name': '审批详情',
                'verbose_name_plural': '审批详情',
            },
        ),
    ]
