# Generated by Django 2.2.3 on 2019-09-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_auto_20190901_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_hosts', to='assets.Service', verbose_name='项目资产组'),
        ),
    ]
