# Generated by Django 2.2.3 on 2019-10-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_auto_20190909_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.SmallIntegerField(choices=[(0, '按机房'), (1, '按占比'), (2, '按定量')], default=0, verbose_name='灰度方式')),
                ('hosts', models.CharField(blank=True, max_length=1000, null=True, verbose_name='灰度机器')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_abtest', to='release.Project', verbose_name='业务')),
            ],
            options={
                'verbose_name': '灰度方式',
                'verbose_name_plural': '灰度方式',
            },
        ),
    ]
