# Generated by Django 2.2.3 on 2019-10-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0006_abtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_publisher', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='record',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_submitter', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
    ]
