# Generated by Django 2.2.3 on 2019-10-12 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0008_auto_20191012_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approve_desc',
            field=models.TextField(blank=True, null=True, verbose_name='审核说明'),
        ),
        migrations.AddField(
            model_name='record',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_approver', to=settings.AUTH_USER_MODEL, verbose_name='审核者'),
        ),
    ]
