# Generated by Django 2.2.3 on 2019-10-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0009_auto_20191012_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApproveDetail',
        ),
    ]
