# Generated by Django 2.2.3 on 2019-10-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20190901_1531'),
        ('release', '0012_auto_20191013_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc_abtest', to='assets.IDC', verbose_name='机房'),
        ),
        migrations.AddField(
            model_name='abtest',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='占比'),
        ),
    ]
