# Generated by Django 2.2.3 on 2019-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0014_project_test_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='exclude_file',
            field=models.TextField(blank=True, null=True, verbose_name='排除文件'),
        ),
    ]
