# Generated by Django 2.2.3 on 2019-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_auto_20191021_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pre_script',
            field=models.FilePathField(blank=True, match='\\.py$|\\.rb$|\\.sh$|\\.php$|\\.java$|\\.pl$|\\.go$', null=True, path='/data/.virtualenvs/small_platform/project_scripts', recursive=True, verbose_name='前执行脚本'),
        ),
    ]
