# Generated by Django 2.2.3 on 2019-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0016_auto_20191025_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='post_script',
            field=models.FilePathField(blank=True, match='\\.py$|\\.rb$|\\.sh$|\\.php$|\\.java$|\\.pl$|\\.go$', null=True, path='/data/.virtualenvs/small_platform/project_scripts', recursive=True, verbose_name='后执行脚本'),
        ),
    ]
