# Generated by Django 2.2.3 on 2019-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0017_auto_20191025_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='released_hosts',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='已发布的机器'),
        ),
    ]
