# Generated by Django 2.2.3 on 2019-10-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0018_auto_20191025_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='日志')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_log', to='release.Record', verbose_name='发布记录')),
            ],
            options={
                'verbose_name': '发布记录日志',
                'verbose_name_plural': '发布记录日志',
            },
        ),
    ]
