# Generated by Django 2.2.3 on 2019-10-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0019_recordlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test_hosts',
        ),
        migrations.AddField(
            model_name='project',
            name='test_host',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='测试机器'),
        ),
    ]
