# Generated by Django 2.2.3 on 2019-10-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0020_auto_20191030_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_record', to='release.Project', verbose_name='所属业务'),
        ),
    ]
