# Generated by Django 2.2.3 on 2019-11-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0021_auto_20191031_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_script_args',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='后脚本参数'),
        ),
        migrations.AddField(
            model_name='project',
            name='pre_script_args',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='前脚本参数'),
        ),
    ]
