# Generated by Django 2.2.3 on 2019-12-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0022_auto_20191101_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '待审核'), (1, '已审核'), (2, '已灰度'), (3, '已发布'), (4, '作废')], default=0, verbose_name='记录状态'),
        ),
    ]
