# Generated by Django 2.2.3 on 2019-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0023_auto_20191211_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='业务名称'),
        ),
    ]
