# Generated by Django 2.2.3 on 2019-12-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0025_auto_20191212_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='hosts',
            new_name='service_hosts',
        ),
    ]
