# Generated by Django 2.2.3 on 2019-12-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0026_auto_20191213_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_hosts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_project', to='assets.Service', verbose_name='项目资产组'),
        ),
    ]
