# Generated by Django 2.2.3 on 2019-12-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0027_auto_20191213_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='service_hosts',
            new_name='hosts',
        ),
    ]
