# Generated by Django 2.2.3 on 2020-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0030_auto_20200305_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='test_branch',
            field=models.CharField(default='master', max_length=32, verbose_name='测试环境分支名称'),
        ),
    ]
