# Generated by Django 2.2.3 on 2020-03-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0032_git_git_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='git_pid',
            field=models.IntegerField(blank=True, null=True, verbose_name='GitLab ID'),
        ),
    ]
