# Generated by Django 2.2.3 on 2020-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0033_auto_20200305_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='if_operator',
            field=models.BooleanField(default=False, verbose_name='是否需要运维介入'),
        ),
        migrations.AddField(
            model_name='record',
            name='what_operate',
            field=models.TextField(blank=True, null=True, verbose_name='运维操作说明或内容'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, '待介入'), (0, '待审核'), (1, '待发布'), (2, '已灰度'), (3, '已发布'), (4, '作废')], default=0, verbose_name='记录状态'),
        ),
    ]
