# Generated by Django 2.2.3 on 2020-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0034_auto_20200307_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='业务名称')),
                ('monday', models.BooleanField(default=True, verbose_name='星期一')),
                ('tuesday', models.BooleanField(default=True, verbose_name='星期二')),
                ('wednesday', models.BooleanField(default=True, verbose_name='星期三')),
                ('thursday', models.BooleanField(default=True, verbose_name='星期四')),
                ('friday', models.BooleanField(default=False, verbose_name='星期五')),
                ('saturday', models.BooleanField(default=False, verbose_name='星期六')),
                ('sunday', models.BooleanField(default=False, verbose_name='星期日')),
            ],
            options={
                'verbose_name': '权限设置',
                'verbose_name_plural': '权限设置',
            },
        ),
    ]
