# Generated by Django 2.2.3 on 2020-07-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0035_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file', models.FileField(upload_to='release_scripts', verbose_name='脚本文件')),
            ],
            options={
                'verbose_name': '脚本文件',
                'verbose_name_plural': '脚本文件',
            },
        ),
    ]
