# Generated by Django 2.2.3 on 2020-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0036_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='git',
            name='url',
            field=models.CharField(max_length=100, verbose_name='仓库代码地址'),
        ),
        migrations.AlterField(
            model_name='wget',
            name='url',
            field=models.CharField(max_length=100, verbose_name='下载地址'),
        ),
    ]
